# Generated by Django 3.2.10 on 2022-06-20 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DBModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('md_name', models.CharField(max_length=50, null=True)),
                ('md_video_title', models.CharField(max_length=150, null=True)),
                ('md_ts_chat', models.TextField(null=True)),
                ('md_dl_state', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
