# Generated by Django 3.2.10 on 2021-12-20 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='borderdatamodel',
            name='md_r_corder',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
