# Generated by Django 3.1.7 on 2021-03-24 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchquerymodel',
            name='md_analysis_pages_end',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='searchquerymodel',
            name='md_analysis_pages_str',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
