# Generated by Django 3.2.10 on 2022-06-09 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DBModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('md_name', models.CharField(max_length=50, null=True)),
                ('md_r_day', models.TextField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='BorderDataModel',
        ),
    ]
