# Generated by Django 3.2.10 on 2022-06-09 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_auto_20220609_1723'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dbmodel',
            old_name='md_r_day',
            new_name='md_ts_chat',
        ),
    ]
