# Generated by Django 3.1.7 on 2021-03-24 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_auto_20210324_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchquerymodel',
            name='md_analysis_pages_radio',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='searchquerymodel',
            name='md_analysis_pages_end',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='searchquerymodel',
            name='md_analysis_pages_str',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
