# Generated by Django 3.1.7 on 2021-03-24 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_auto_20210324_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchquerymodel',
            name='md_ana_end_spec',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='searchquerymodel',
            name='md_radio_ana_end_spec',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
