# Generated by Django 3.2.10 on 2022-06-12 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_dbmodel_md_video_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='dbmodel',
            name='md_video_recorded_at_jst',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
