# Generated by Django 3.1.7 on 2021-03-25 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_auto_20210325_0204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchquerymodel',
            name='md_analysis_pages',
        ),
    ]
