# Generated by Django 3.2.10 on 2022-06-13 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0006_auto_20220612_2334'),
    ]

    operations = [
        migrations.AddField(
            model_name='dbmodel',
            name='md_dl_state',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
