# Generated by Django 3.1.7 on 2021-04-13 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0007_searchquerymodel_md_alert_sw'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDataModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('md_line_token', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
