# Generated by Django 3.2.10 on 2022-06-18 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0007_dbmodel_md_dl_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='dbmodel',
            name='md_video_title',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
