# Generated by Django 3.1.7 on 2021-04-20 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0010_userdatamodel_md_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='GotDataModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('md_name', models.CharField(max_length=50, null=True)),
                ('md_cancel_border', models.TextField(null=True)),
                ('md_reserve_border', models.TextField(null=True)),
            ],
        ),
    ]
