# Generated by Django 3.1.7 on 2021-04-20 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0011_gotdatamodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdatamodel',
            name='md_to_email',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
