# Generated by Django 3.1.7 on 2021-04-20 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0012_userdatamodel_md_to_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GotDataModel',
            new_name='BorderDataModel',
        ),
    ]
