# Generated by Django 3.1.7 on 2021-04-21 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0013_auto_20210420_2022'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SearchQueryModel',
        ),
    ]
